# Generated by Django 4.2.2 on 2023-06-26 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name='ингредиент'
                    ),
                ),
                (
                    'measurement_unit',
                    models.CharField(
                        max_length=20, verbose_name='единица измерения'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='IngredientInRecipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'amount',
                    models.FloatField(
                        verbose_name='количество ингредиента в рецепте'
                    ),
                ),
                (
                    'ingredient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='recipes.ingredient',
                        verbose_name='ингредиент',
                    ),
                ),
            ],
            options={
                'default_related_name': '%(class)s',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'cooking_time',
                    models.IntegerField(verbose_name='время приготовления'),
                ),
                (
                    'image',
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to='recipes/images',
                        verbose_name='фото готового блюда',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200, verbose_name='название рецепта'
                    ),
                ),
                (
                    'pub_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата публикации'
                    ),
                ),
                ('text', models.TextField(verbose_name='описание рецепта')),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='автор рецепта',
                    ),
                ),
                (
                    'ingredients',
                    models.ManyToManyField(
                        through='recipes.IngredientInRecipe',
                        to='recipes.ingredient',
                        verbose_name='список ингредиентов рецепта',
                    ),
                ),
            ],
            options={
                'ordering': ('-pub_date',),
                'default_related_name': '%(class)s',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=50, unique=True, verbose_name='метка'
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        max_length=16, unique=True, verbose_name='цвет метки'
                    ),
                ),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='пользователь-автор',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscriber',
                        to='recipes.recipe',
                        verbose_name='пользователь-подписчик',
                    ),
                ),
            ],
            options={
                'default_related_name': '%(class)s',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(
                to='recipes.tag', verbose_name='список меток'
            ),
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='recipes.recipe',
                verbose_name='рецепт',
            ),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='владелец списка избранных рецептов',
                    ),
                ),
                (
                    'recipe',
                    models.ManyToManyField(
                        to='recipes.recipe',
                        verbose_name='список избранных рецептов',
                    ),
                ),
            ],
            options={
                'default_related_name': '%(class)s',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='владелец списка рецептов для закупки продуктов',
                    ),
                ),
                (
                    'recipe',
                    models.ManyToManyField(
                        to='recipes.recipe',
                        verbose_name='список рецептов для закупки продуктов',
                    ),
                ),
            ],
            options={
                'default_related_name': '%(class)s',
            },
        ),
    ]
