# Generated by Django 4.2.2 on 2023-06-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_alter_subscribe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
