# Generated by Django 4.2.2 on 2023-10-09 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_alter_cart_owner_alter_cart_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(
                max_length=7,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Tag color hex code invalid.',
                        regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$',
                    )
                ],
                verbose_name='цвет метки',
            ),
        ),
    ]
