# Generated by Django 4.2.2 on 2023-07-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0003_recipe_favorite_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(
                max_length=7, unique=True, verbose_name='цвет метки'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                max_length=200, unique=True, verbose_name='метка'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                max_length=200, unique=True, verbose_name='слаг'
            ),
        ),
    ]
