# Generated by Django 4.2.2 on 2023-09-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0006_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=models.BooleanField(
                default=False, verbose_name='рецепт в списке избранных'
            ),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(
                default=False, verbose_name='рецепт в списке покупок'
            ),
        ),
    ]
