# Generated by Django 4.2.2 on 2023-10-06 09:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200, verbose_name='ингредиент'
                    ),
                ),
                (
                    'measurement_unit',
                    models.CharField(
                        max_length=200, verbose_name='единица измерения'
                    ),
                ),
            ],
            options={
                'default_related_name': '%(class)s',
            },
        ),
        migrations.CreateModel(
            name='IngredientInRecipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'amount',
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name='количество ингредиента в рецепте',
                    ),
                ),
                (
                    'ingredient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='recipes.ingredient',
                        verbose_name='ингредиент',
                    ),
                ),
            ],
            options={
                'default_related_name': '%(class)s',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200, unique=True, verbose_name='метка'
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        max_length=7, unique=True, verbose_name='цвет метки'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        max_length=200, unique=True, verbose_name='слаг'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='пользователь-автор',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscriber',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='пользователь-подписчик',
                    ),
                ),
            ],
            options={
                'default_related_name': '%(class)s',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'cooking_time',
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name='время приготовления',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to='recipes/images',
                        verbose_name='фото готового блюда',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200, verbose_name='название рецепта'
                    ),
                ),
                (
                    'pub_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата публикации'
                    ),
                ),
                ('text', models.TextField(verbose_name='описание рецепта')),
                (
                    'is_favorited',
                    models.BooleanField(
                        default=False, verbose_name='рецепт в списке избранных'
                    ),
                ),
                (
                    'is_in_shopping_cart',
                    models.BooleanField(
                        default=False, verbose_name='рецепт в списке покупок'
                    ),
                ),
                ('favorite_count', models.IntegerField(blank=True, default=0)),
                (
                    'in_shopping_cart_count',
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='автор рецепта',
                    ),
                ),
                (
                    'ingredients',
                    models.ManyToManyField(
                        related_name='recipe_ingredients',
                        through='recipes.IngredientInRecipe',
                        to='recipes.ingredient',
                        verbose_name='список ингредиентов рецепта',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        to='recipes.tag', verbose_name='список меток'
                    ),
                ),
            ],
            options={
                'ordering': ('-pub_date',),
                'default_related_name': '%(class)s',
            },
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='recipes.recipe',
                verbose_name='рецепт',
            ),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='owner',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='владелец списка избранных рецептов',
                    ),
                ),
                (
                    'recipe',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='recipes.recipe',
                        verbose_name='список избранных рецептов',
                    ),
                ),
            ],
            options={
                'default_related_name': '%(class)s',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='владелец списка рецептов для закупки продуктов',
                    ),
                ),
                (
                    'recipe',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='recipes.recipe',
                        verbose_name='список рецептов для закупки продуктов',
                    ),
                ),
            ],
            options={
                'default_related_name': '%(class)s',
            },
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(
                fields=('author', 'user'), name='unique_subscribe'
            ),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(
                check=models.Q(('author', models.F('user')), _negated=True),
                name='author_is_not_user',
            ),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(
                fields=('owner', 'recipe'), name='unique_favorite_recipe'
            ),
        ),
    ]
