# Generated by Django 4.2.2 on 2023-10-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0004_remove_cart_unique_cart_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorite_count',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='in_shopping_cart_count',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
        migrations.AddConstraint(
            model_name='ingredientinrecipe',
            constraint=models.UniqueConstraint(
                fields=('ingredient', 'recipe'),
                name='unique_ingredientinrecipe',
            ),
        ),
    ]
